# Generated by Django 3.0.5 on 2020-04-17 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200417_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 5, 50, 51, 787785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(default=datetime.datetime(2020, 4, 17, 5, 50, 51, 787785, tzinfo=utc)),
        ),
    ]
