# Generated by Django 3.0.5 on 2020-04-18 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200417_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 4, 18, 0, 39, 7, 683528, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(default=datetime.datetime(2020, 4, 18, 0, 39, 7, 683528, tzinfo=utc)),
        ),
    ]
