# Generated by Django 3.0.5 on 2020-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200418_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(),
        ),
    ]
